data = [
    {
        "name": "Instagram",
        "follower_count": 346,
        "description": "Soziale Medien Plattform",
        "country": "USA",
    },
    {
        "name": "Cristiano Ronaldo",
        "follower_count": 215,
        "description": "Fußballspieler",
        "country": "Portugal",
    },
    {
        "name": "FC Bayern München",
        "follower_count": 120,
        "description": "Fußballverein",
        "country": "Deutschland",
    },
    {
        "name": "Borussia Dortmund",
        "follower_count": 45,
        "description": "Fußballverein",
        "country": "Deutschland",
    },
    {
        "name": "Manuel Neuer",
        "follower_count": 15,
        "description": "Fußballtorwart",
        "country": "Deutschland",
    },
    {
        "name": "Thomas Müller",
        "follower_count": 14,
        "description": "Fußballspieler",
        "country": "Deutschland",
    },
    {
        "name": "Mesut Özil",
        "follower_count": 24,
        "description": "Ehemaliger Fußballspieler",
        "country": "Deutschland",
    },
    {
        "name": "SAP",
        "follower_count": 3,
        "description": "Softwareunternehmen",
        "country": "Deutschland",
    },
    {
        "name": "BMW",
        "follower_count": 35,
        "description": "Automobilhersteller",
        "country": "Deutschland",
    },
    {
        "name": "Mercedes-Benz",
        "follower_count": 38,
        "description": "Automobilhersteller",
        "country": "Deutschland",
    },
    {
        "name": "Volkswagen",
        "follower_count": 32,
        "description": "Automobilhersteller",
        "country": "Deutschland",
    },
    {
        "name": "Adidas",
        "follower_count": 28,
        "description": "Sportartikelhersteller",
        "country": "Deutschland",
    },
    {
        "name": "Puma",
        "follower_count": 25,
        "description": "Sportartikelhersteller",
        "country": "Deutschland",
    },
    {
        "name": "Angela Merkel",
        "follower_count": 12,
        "description": "Ehemalige Bundeskanzlerin",
        "country": "Deutschland",
    },
    {
        "name": "Berlin",
        "follower_count": 6,
        "description": "Hauptstadt",
        "country": "Deutschland",
    },
    {
        "name": "Deutsche Bahn",
        "follower_count": 4,
        "description": "Eisenbahnunternehmen",
        "country": "Deutschland",
    },
    {
        "name": "Lufthansa",
        "follower_count": 7,
        "description": "Fluggesellschaft",
        "country": "Deutschland",
    },
    {
        "name": "Bayer 04 Leverkusen",
        "follower_count": 8,
        "description": "Fußballverein",
        "country": "Deutschland",
    },
    {
        "name": "RB Leipzig",
        "follower_count": 9,
        "description": "Fußballverein",
        "country": "Deutschland",
    },
    {
        "name": "Helene Fischer",
        "follower_count": 10,
        "description": "Sängerin",
        "country": "Deutschland",
    },
    {
        "name": "Rammstein",
        "follower_count": 11,
        "description": "Rockband",
        "country": "Deutschland",
    },
    {
        "name": "DW Deutsch",
        "follower_count": 5,
        "description": "Nachrichtenorganisation",
        "country": "Deutschland",
    },
    {
        "name": "ZDF",
        "follower_count": 3,
        "description": "Fernsehsender",
        "country": "Deutschland",
    },
    {
        "name": "ARD",
        "follower_count": 3,
        "description": "Fernsehsender",
        "country": "Deutschland",
    },
]
